Predefined field data types and associated wire encodings
=========================================================
v2023.38

The basic wire-encoding does not care about field types. Those must be learned by looking into the declarations of the protocol definition files. The wire-encoding treats all data types just as opaque octet-strings.

The following list gives a list of type names which can be used to declare particular data type encodings for fields within protocol definition files.

Every encoding is identified by a UUID and a recommended symbolic name. The name is not necessarily unique. The UUID always is.

If a name clash arises from this within a project, the names can either be changed arbitrarily. Or enough leading characters from the UUID may be added to the names in order to make them unique within the project.

For instance, it there are two encodings with exemplary UUIDs "tbh9kdft04rzsisyiwm9hur9p" and "tidawgy2728k3033lv4l8ujk4" used in the same protocol definition but both recommend the same name "angle", then one could be named "angle" and the other "angle_alt". Or one could be named "angle_tb" and the other one "angle_ti". Or, if one of both encodings is clearly more prominent than the other one, it could keep its original name while the others get UUID-derived suffixes: "angle" (for "tbh9kdft04rzsisyiwm9hur9p") and "angle_ti" (for "tidawgy2728k3033lv4l8ujk4"). Note that those are just suggestions. Do what you like. Just ensure the reader of the protocol definition can unambiguously associate all used type names with UUIDs.

The UUIDs used in this document are standard DCE UUIDs, also called GUIDs in the Microsoft realm. However, they have been encoded using a base-35 alphabet for better compactness and identifier-suffix friendliness.

The conversion removed all dashes and braces from the usual hex-based standard representation of GUIDs and treated the result as a 128-bit hexadecimal number. This number has then converted into base-35 number using an alphabet consisting of all digits and lower-case letters (sorted by their ASCII code value) except for the letter "o" ("oh") which has been omitted from the alphabet.

You are invited to invent your own data types in addition to those declared here. You are not required to also specify base-35 UUIDs for your types. You can also use the usual hex-based GUID format, with or without the dashes, with or without the braces. None of those UUID variants can be confused due to their different string lengths. In other words, the string lengths create name different namespaces, and every namespace can choose a different UUID representation encoding. All known existing UUID representation formats have different lengths to the best of my knowledge, so they should all work.

Some UUID encodings will require case-insensitive comparisons while other will not. This shall be decided as follows: Take the string representations of several UUIDs of the same encoding variant and remove all structuring characters like dashes, braces etc. which are common. Then those stripped strings shall all have the same length `L`. Now solve the equation `log(2 ** 128) / log(B) = L` and determine the unknown `B`. `log` can be the logarithm to any base, it does not matter which base it is as long as it is the same for both function calls. Replace `B := ceiling(B)`. Further assume that `B` is the base used for the encoding; i. e. the size of the alphabet used. Finally assume that all bases of at least 52 will include both upper- and lower-case characters within their encoding, and must therefore not be compared case-insensitively. Otherwise the encoding can be compared case-insensitively. When still in doubt, compare case-sensitively. This is more defensive. If you do not find a match anywhere, you can still retry with a case-insensitive search. Of course, all this only matters if the UUID encoding is neither explained nor obvious. Otherwise, one could just decode the UUIDs into their binary forms and compare those bit by bit. It is recommended to include a short explanation of the UUID encoding scheme used in a protocol definition file unless it is one of the widely-used GUID representations or the base-35 encoding used in this document.

There is no obligation to use the recommended names. Name them anything you like in your protocol definition file. Just keep the UUID.

It is even allowed to use different names for the same encoding within your protocol definition. This kind of aliasing is possibly be both names sharing the same UUID.

IMPORTANT: Always include a name-to-UUID mapping as part of your protocol definitions! Never use a wire-type encoding name without somewhere within the document associating it with a UUID. The used type names are only unique (or aliases of unique types) inside the protocol definition. But in order to associate a unique unamiguous binary encoding with the protocol, the UUID of this encoding *must* also be known! Or to put it differently: Without a type-to-UUID mapping, your protocol definition is basically worthless because no-one can be sure about the details of the binary encoding.

Some of the encoding descriptions refer to other types also defined in this document. For brevity, only the recommended names are used in the text. If copying the descriptions somewhere else, be sure to add the omitted UUIDs of the referenced names in order to become unambiguous independent of context.

* A nested message. This is actually not a particular type, but is rather represented by the type given to a different "message" declaration. Such defined message types can be used as fields in other messages. This is encoded as a byte string, i. e. the field is encoded like a string and contains the complete binary encoding of the nested message as its contents.

* {empty}
+
include::proto_types/uint_gyic709md7c9icf8wl1akdcq7.txt[]

* {empty}
+
include1::proto_types/int_gyj6jm8psufclh72ka1unkbct.txt[]

* {empty}
+
include::proto_types/string_smap94sqt5kfn6pee6ash6qr1.txt[]

* {empty}
+
include::proto_types/locale_string_smbgv847g4fyvel5tfir6gtr5.txt[]

* {empty}
+
include::proto_types/any_string_gyjyupanxic0dp96zzw4cw2zk.txt[]

* {empty}
+
include::proto_types/octetstring_smc8gywnq3bpmutkpgqawm870.txt[]

* {empty}
+
include::proto_types/bytestring_smd1ish29drr4cu3mvj84pfva.txt[]

* {empty}
+
include::proto_types/opaque_gyksmf950bwn6tnz4cxql7u3d.txt[]

* {empty}
+
include::proto_types/utf8_string_gyllbf12kq6ssjfe49w32usk7.txt[]

* {empty}
+
include::proto_types/utf16_le_string_gymedz491l39hhth0nc6bddlx.txt[]

* {empty}
+
include::proto_types/utf16_be_string_gyn6scskqnk1tq3lez6kk4qrr.txt[]

* {empty}
+
include::proto_types/utf16_default_le_string_gynzvmdk34xys2m0r32g2kn32.txt[]

* {empty}
+
include::proto_types/utf16_default_be_string_gypspmn9p11x6aqjfpe8nwmxe.txt[]

* {empty}
+
include::proto_types/latin1_string_gyqjs023utju33x1p5s7cr5vz.txt[]

* {empty}
+
include::proto_types/ascii_gyrbdijh4rkvhd68pptqwftne.txt[]

* {empty}
+
include::proto_types/ebcdic_gys3ghtk7lmvezg4wcjnz22hn.txt[]

* {empty}
+
include::proto_types/boolean_gysvj9skbfv6001rncyt2fh10.txt[]

* {empty}
+
include::proto_types/float_gytn2g2vd2uyanuk4e7greqj7.txt[]

* {empty}
+
include::proto_types/double_gyufjdmmkjrjjmj5up181gvlu.txt[]

* {empty}
+
include::proto_types/pfloat_gyv8ad8lkl2eyhz7yv2z93ucv.txt[]

* {empty}
+
include::proto_types/decimal_gyw00v7lc07nzkqyw737draus.txt[]

* {empty}
+
include::proto_types/dfix1_gywrh6hvbc1bpe9yfeuhyz4ca.txt[]

* {empty}
+
include::proto_types/dfix2_gyxhzrim4ty5hrlziq9ykh6yr.txt[]

* {empty}
+
include::proto_types/dfix4_gyyaivlt2292ecgiy53nz5l32.txt[]

* {empty}
+
include::proto_types/rational_gyz30dlebhg9y0dekh413kn2p.txt[]

* {empty}
+
include::proto_types/bitvector_gyzwhakfv1wrpcrgrpg1dn25h.txt[]

* {empty}
+
include::proto_types/serialdate_gz0mtxwagc4rkfrejebr2n76l.txt[]

* {empty}
+
include::proto_types/tzoffset_gz1fptrrtfvz54bv0re1pd8nq.txt[]

* {empty}
+
include::proto_types/serialtime_gz26jdfmprixgjci9vuwurs19.txt[]

* {empty}
+
include::proto_types/localdatetime_gz2yqknjch8pskwz29knf30ag.txt[]

* {empty}
+
include::proto_types/globaldatetime_gz3qrkpbplr3dtik2cs3au3i7.txt[]

* {empty}
+
include::proto_types/ubcd4_0_gz4iq2ncpil0busszjyyzcayi.txt[]

* {empty}
+
include::proto_types/ubcd8_0_gz5ardls06vfgguraht0dl6wf.txt[]

* {empty}
+
include::proto_types/ubcd_a_0_gz5ardls06vfgguraht0dl6wf.txt[]

* {empty}
+
include::proto_types/ubcd4_1_sm5t0k8j8eq828z4tyk15kwji.txt[]

* {empty}
+
include::proto_types/ubcd4_2_sm6lj95tinvlr7zf6k2phnkvt.txt[]

* {empty}
+
include::proto_types/ubcd4_4_sm7f9ad5z6e8309xvz9b4nw1c.txt[]

* {empty}
+
include::proto_types/bcd_a_sm89e7p3ex3k9zc670yzb7wlu.txt[]

* {empty}
+
include::proto_types/ubcd4e4_sm923fbun8pipd4ctcibiuzb6.txt[]

* {empty}
+
include::proto_types/s10bcd4e4_sm9winegqnwb5kyfrqxcf4k8r.txt[]

* {empty}
+
include::proto_types/s9bcd4e4_smekzqub39l4p1r5bphthgb4i.txt[]

* {empty}
+
include::proto_types/flash28_f1i4teamzt57f0xbuvxnn5uzp.txt[]

* {empty}
+
include::proto_types/flash56_bz82xqjb07ld5ggj7wx2ncvb6.txt[]


Adding custom type names
------------------------

You are free to add more custom encodings! Just check with the above list in order to make sure you didn't invent the wheel again. (In that case, please use the existing UUID, although it is OK to use your custom name for the same encoding.) Thanks the the UUID, there is no danger that your encoding clashes with someone else's. You can use any name for your new encoding, even if it collides with one of the names specified in this document. Just be sure to always include a name-to-UUID mapping in your protocol definition document. This mapping makes the types used in your definition unambiguous, even if you choose to rename some of the human-readable type names in your protocol definition. It is recommended, however, to only use alphanumerics and underscores in your custom names, and the name should start with a regular alphabetic letter. Name your own type "int32" or "complex" if you like. As long as you do not forget to generate a UUID for every new wire type encoding and include a name-UUID-mapping for all used encodings within your protocol definition document, it does not matter.


Notable missing predefined data types
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Even though it is possible to add any desired missing data type as custom type names, I will explain here why some popular data types have not been predefined.


int32, int64 etc.
-----------------

The existing "int"/"uint" can represent each of those without any disadvantage in terms of encoding efficiency. Together with the "zero-leftpad"-attribute declaration fixed-width encodings of are also possible.

utf32_string
------------

UTF-32 encoding is only interesting as an in-memory representation for simpler processing. It makes no sense as an external encoding, because there is no UTF-32 encoding which cannot be replaced by a same-length or shorter equivalent UTF-16 encoding. An UTF-32 encoding of some text is always larger or the same length as UTF-16, but will never save space. Generally, western languages are most efficiently encoded as UTF-8, while eastern CJK languages are most efficiently encoded as UTF-16.


UNICODE normalization qualifiers
--------------------------------

For those of the above UNICODE-based string types which can potentially represent UNICODE characters normalized as NFD, the type name may optionally be preceded by one of the following qualifiers: NFC, NFD, NFKC, NFKD. Those specify that the string values for that field are required to be normalized according to the UNICODE normalization format of the same name. If you have no idea what UNICODE normalization is, you probably won't need it. The qualifiers mean that any specified default constant for such a string must be normalized in the same way, because the protocol compiler won't convert anything. However, it MAY present an error in such a case (more likely though it won't care). Neither is the run-time required to check for normalization compliance (though it might). Therefore, those qualifiers are primarily a hint to the human reader what sort of normalization is expected/required.


UNICODE compression qualifiers
------------------------------

For those of the above UNICODE-based string types which uses multibyte encodings for at least some of its UNICODE characters, and preceding the UNICODE normalization qualifier (if any, as it is optional), one of two further optional qualifiers is allowed: "SCSU-compressed" and "BOCU-1-compressed". They declare that the UNICODE string in this field is expected to be compressed with the compression scheme named after the qualifier. It also means that any declared default value will be encoded this way before actually being used. Like the normalization qualifiers, those compression qualifiers will have no effect on the run-time or the protocol compiler, other than compressing any associated default string literal in the specified way. And the first version of the protocol compiler certainly won't support that, meaning that for now string fields with that qualifier must not have an explicit default value.


Current state of implementation
-------------------------------

Finally note that most of the encodings above have not actually been implemented yet. I will do so once I actually need them for the first time. Of course, you are free to implement them yourself, provided that the generated encodings comply with and do not contradict the above definitions.
